services:
  octoprint:
    image: octoprint/octoprint:latest
    restart: unless-stopped
    volumes:
      - octoprint:/octoprint
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/video0
    environment:
      - ENABLE_MJPG_STREAMER=true
      - CAMERA_DEV=/dev/video0
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    ports:
      - 443:443
      - 80:8080
    links:
      - octoprint:octoprint
    depends_on:
      - octoprint

volumes:
  octoprint:
