# syntax=docker/dockerfile:1
FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE=1
RUN pip install --no-cache-dir OctoPrint

RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 5000
ENTRYPOINT [ "python", "-m", "octoprint" ]
CMD [ "serve", "--iknowwhatimdoing" ]
