# syntax=docker/dockerfile:1
FROM python:3.10

RUN adduser octoprint
USER octoprint

ENV PYTHONDONTWRITEBYTECODE=1
RUN pip install --no-cache-dir OctoPrint

EXPOSE 5000
ENTRYPOINT [ "python", "-m", "octoprint" ]
CMD [ "serve" ]
